services:
  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-service:/app
    networks:
      - ai_net
  
  backend:
    build:
      context: ./backend-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend-service/app:/app
    networks:
      - ai_net
  
  db:
    build:
      context: ./db-service
      dockerfile: Dockerfile.dev
    env_file:
      - ./db-service/.env
    ports:
      - "5432:5432"
    networks:
      - ai_net

networks:
  ai_net:
    external: true

